### ISSUE TITLE
Minimizing Browser Permissions

### ISSUE THREAD

**Issue by ChanceHarrison** [qiweiii/github-custom-notifier#2]
Hi there. I see that `github-custom-notifier` requires the "Access browser tabs" permission on Firefox. This seems like an unnecessarily broad permission to require, especially given that it's unclear to the end-user why such permission is necessary. This naturally raises concerns among users regarding the privacy of their browsing data.

From a more technically nuanced perspective:

Looking at [src/lib/services-ext/tabs.ts](https://github.com/qiweiii/github-custom-notifier/blob/main/src/lib/services-ext/tabs.ts), the `openTab` function will check for the `tabs` permission and will create a new tab at the specified URL if that permission is granted.

However, my understanding is that this is unnecessary.

> You can use most of this API without any special permission ([source](https://developer.mozilla.org/en-US/docs/Mozilla/Add-ons/WebExtensions/API/tabs))

Aside from that, there is an unused `queryTab` function.

Based on this, I would suggest modifying the extension such that the `tabs` permission is not requested.

What do you think? Thanks for your time.

**Comment by qiweiii** [comment]
Yes, you are right, maybe we don't need that permission, need to remove it from manifest and check if it works on chrome and edge as well.

**Comment by gschlager** [comment]
@qiweiii Any update on this?

**Comment by qiweiii** [comment]
will try to make a release soon

**Comment by qiweiii** [comment]
pending review on chrome and firefox stores, should be auto published and updated in user browsers in a few days

**Comment by Johndoe109** [comment]
good first issue
